<a href="https://colab.research.google.com/github/paras-aghija/python-DS/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [2]:
import numpy as np

### Numpy Basics


In [6]:
a = np.array([1,2,3,4,5,6])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [11]:
b = np.array([[1,1],[2,2],[3,3],[4,4],[5,5]])
print(b)
print(b.shape)
print(b[1][1])

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]
(5, 2)
2


In [12]:
z = np.zeros((3,3))
print(z)
print(type(z))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [13]:
o = np.ones((4,5))
print(o)
print(type(o))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [14]:
c = np.full((3,4), 7, int)
print(c)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [17]:
# identity matrix
d = np.eye(4,dtype=int)
print(d)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [21]:
# random matrix
r = np.random.random((2,3))
print(r)
print(r[1][2])
print(r[0,1])

[[0.23082667 0.48558717 0.8186255 ]
 [0.55224085 0.06029013 0.85298065]]
0.8529806545835911
0.48558716579921823


In [26]:
x = np.random.random((4,5))
print(x)
print()
print(x[ : , 2 ])
print(x[ 3, : ])

[[0.41026939 0.30087661 0.47962824 0.05161657 0.31322846]
 [0.72264261 0.38352044 0.89277241 0.09389427 0.92609322]
 [0.53970748 0.01170135 0.95392123 0.10546352 0.70581922]
 [0.10713726 0.87099263 0.04733133 0.51184236 0.8665779 ]]

[0.47962824 0.89277241 0.95392123 0.04733133]
[0.10713726 0.87099263 0.04733133 0.51184236 0.8665779 ]


In [28]:
x[2, 3:] = 1
print(x)

[[0.41026939 0.30087661 0.47962824 0.05161657 0.31322846]
 [0.72264261 0.38352044 0.89277241 0.09389427 0.92609322]
 [0.53970748 0.01170135 0.95392123 1.         1.        ]
 [0.10713726 0.87099263 0.04733133 0.51184236 0.8665779 ]]


In [31]:
y = np.zeros((3,3), dtype = np.int64)
print(z)
y[1,:] = 5
y[:, -1] = 7
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [32]:
print(y.dtype)

int64


In [33]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [34]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [38]:
print(x*y)
# not dot product

[[ 5 12]
 [21 32]]


In [39]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [40]:
print(np.sqrt(y))

[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [41]:
# Matrix multiplication
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [42]:
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [3]:
# dot multiplication of vectors

a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [4]:
print(sum(a))

10


In [6]:
x = np.array([[1,2], [3,4]])
print(x)
print(np.sum(x))

[[1 2]
 [3 4]]
10


In [7]:
print(np.sum(x, axis=0))

[4 6]


In [8]:
print(np.sum(x, axis=1))

[3 7]


In [9]:
# stacking of arrays
print(a)
b**=2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [10]:
np.stack((a,b), axis=1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [16]:
x = np.stack((a,b), axis=0)
print(x)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [18]:
# reshaping arrays

print(x)
x = x.reshape((4,2))
print(x)

[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [19]:
x.reshape((8,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 1],
       [ 4],
       [ 9],
       [16]])

In [20]:
x.reshape((8,))

array([ 1,  2,  3,  4,  1,  4,  9, 16])

In [21]:
x.reshape((2,-1))

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [22]:
x.reshape((-1,2))

array([[ 1,  2],
       [ 3,  4],
       [ 1,  4],
       [ 9, 16]])

### Numpy Random Module

In [5]:
a = np.arange(4,11,2)
print(a)

[ 4  6  8 10]


In [14]:
#seed
np.random.seed(1)
# stores the state of random number

In [15]:
np.random.shuffle(a)
print(a)

[5 7 8]


In [16]:
a = np.random.rand(2,3)
print(a)

[[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]


In [17]:
# standard normal distribution
a = np.random.randn(2,3)
print(a)

[[-1.10593508 -1.65451545 -2.3634686 ]
 [ 1.13534535 -1.01701414  0.63736181]]


In [18]:
a = np.random.randint(5,10,3)
print(a)

[7 9 7]


In [19]:
e = np.random.choice([1,2,4,7,11])
print(e)

11


### Statistical Operations

In [20]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [22]:
print(np.min(a))
print(np.min(a, axis=0))
print(np.min(a, axis=1))


0
[1 2 2 0]
[1 0]


In [25]:
print(np.mean(a, axis=1))
print(np.median(a, axis=1))

[2.5  3.75]
[2.5 4. ]


In [29]:
x = np.array([1,5,2,4,0])
print(np.mean(x))
print(np.median(x))

2.4
2.0


In [30]:
w = np.array([1,2,3,4,5])
print(np.average(x, weights=w))

# => 1*1 + 5*2 + 2*3 + 4*4 + 0*5 / 5

2.2


In [31]:
# standard deviation (sigma)

u = np.mean(x)
myStd = np.sqrt(np.mean(abs(x-u)**2))
print(myStd)

#inbuilt

print(np.std(x))

1.854723699099141
1.854723699099141


In [32]:
variance = myStd**2
print(variance)

3.440000000000001


<h3>Q. Given a running stream of numbers, compute mean and variance at any given point</h3>

Solution :

    Derrived formula => Variance = E(x^2) - [E(x)]^2
    E is mean function


Both variance and standard deviation are computed in O(1) time

In [35]:
print(a)
print(a.T) # transpose

[[1 2 3 4]
 [7 6 2 0]]
[[1 7]
 [2 6]
 [3 2]
 [4 0]]


In [37]:
a.ndim # number of dimensions

2

In [39]:
# linspace generates equally spaced given number of elements
np.linspace(5, 10, 5) # generates 5 equally spaced elements within range 5 to 10

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

### Important Links :

- [Numpy Blog](https://docs.google.com/viewerng/viewer?url=https://minio.codingblocks.com/amoeba/233b69fe-3d85-42aa-bafb-9af0d319b98c.pdf)
- [Dphi Numpy](https://dphi.tech/courses/introduction-to-numpy)

### Practice

In [53]:
a = np.array([2, 5, 8, 6, 4, 12, 16, 15])

In [42]:
print(a.ndim)

1


In [43]:
print(np.linspace(17,31,50))

[17.         17.28571429 17.57142857 17.85714286 18.14285714 18.42857143
 18.71428571 19.         19.28571429 19.57142857 19.85714286 20.14285714
 20.42857143 20.71428571 21.         21.28571429 21.57142857 21.85714286
 22.14285714 22.42857143 22.71428571 23.         23.28571429 23.57142857
 23.85714286 24.14285714 24.42857143 24.71428571 25.         25.28571429
 25.57142857 25.85714286 26.14285714 26.42857143 26.71428571 27.
 27.28571429 27.57142857 27.85714286 28.14285714 28.42857143 28.71428571
 29.         29.28571429 29.57142857 29.85714286 30.14285714 30.42857143
 30.71428571 31.        ]


In [54]:
print(a)
a = np.append(a, 16)
print(a)

[ 2  5  8  6  4 12 16 15]
[ 2  5  8  6  4 12 16 15 16]


In [56]:
a = np.delete(a, 6)
print(a)

[ 2  5  8  6  4 12 15 16]


In [61]:
np.random.shuffle(a)
print(a)

[ 5  8  6  2 15 16 12  4]


In [62]:
a = np.sort(a)
print(a)

[ 2  4  5  6  8 12 15 16]


In [63]:
a.reshape(2,-1)

array([[ 2,  4,  5,  6],
       [ 8, 12, 15, 16]])

In [72]:
x = np.array( [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41])
z = np.sort(x)
print(np.delete(z,4))


[ 2  3  7  8 12 13 22 23 25 41 46 54]


In [71]:
x = np.append(x, 53)
x.reshape(2,7)

array([[10,  2,  7,  8,  3, 22, 54],
       [12, 13, 46, 23, 25, 41, 53]])

In [77]:
x = np.random.randint(1, 100, (8,5))
print(x)

[[58 83 97 14 11]
 [24 82  8 25 75]
 [93 21 33 13 66]
 [95 61 25 83 98]
 [ 3 93 99 11 55]
 [97 83 87 71 67]
 [72 49 55 16  6]
 [18 43 21 49 23]]


In [81]:
print(x[0:5:2]) #striding

[[58 83 97 14 11]
 [93 21 33 13 66]
 [ 3 93 99 11 55]]


In [83]:
x = np.arange(25)
x = np.reshape(x,(5,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [89]:
x[1::2, 0::2]

array([[ 5,  7,  9],
       [15, 17, 19]])